name: vq2d
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - asttokens=2.2.1=pyhd8ed1ab_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=pyhd8ed1ab_3
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - ca-certificates=2022.12.7=ha878542_0
  - certifi=2022.12.7=pyhd8ed1ab_0
  - debugpy=1.5.1=py38h295c915_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - executing=1.2.0=pyhd8ed1ab_0
  - ipykernel=6.15.0=pyh210e3f2_0
  - ipython=8.12.0=pyh41d4057_0
  - jedi=0.18.2=pyhd8ed1ab_0
  - jupyter_client=7.0.6=pyhd8ed1ab_0
  - jupyter_core=5.3.0=py38h578d9bd_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.2=h6a678d5_6
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libsodium=1.0.18=h36c2ea0_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.5.6=pyhd8ed1ab_0
  - openssl=1.1.1t=h7f8727e_0
  - parso=0.8.3=pyhd8ed1ab_0
  - pexpect=4.8.0=pyh1a96a4e_2
  - pickleshare=0.7.5=py_1003
  - pip=23.0.1=py38h06a4308_0
  - platformdirs=3.2.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.38=pyha770c72_0
  - prompt_toolkit=3.0.38=hd8ed1ab_0
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pygments=2.15.0=pyhd8ed1ab_0
  - python=3.8.16=h7a1cb2a_3
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.8=2_cp38
  - pyzmq=19.0.2=py38ha71036d_2
  - readline=8.2=h5eee18b_0
  - setuptools=65.6.3=py38h06a4308_0
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.41.1=h5eee18b_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - tk=8.6.12=h1ccaba5_0
  - tornado=6.1=py38h0a891b7_3
  - traitlets=5.9.0=pyhd8ed1ab_0
  - typing-extensions=4.5.0=hd8ed1ab_0
  - typing_extensions=4.5.0=pyha770c72_0
  - wcwidth=0.2.6=pyhd8ed1ab_0
  - wheel=0.38.4=py38h06a4308_0
  - xz=5.2.10=h5eee18b_1
  - zeromq=4.3.4=h9c3ff4c_1
  - zlib=1.2.13=h5eee18b_0
  - pip:
    - appdirs==1.4.4
    - blessed==1.20.0
    - charset-normalizer==3.1.0
    - click==8.1.3
    - contourpy==1.0.7
    - cycler==0.11.0
    - decord==0.6.0
    - docker-pycreds==0.4.0
    - easydict==1.10
    - edict==0.51
    - einops==0.6.0
    - filelock==3.10.7
    - fonttools==4.39.2
    - gitdb==4.0.10
    - gitpython==3.1.31
    - gpustat==1.0.0
    - huggingface-hub==0.13.3
    - idna==3.4
    - imageio==2.26.1
    - imageio-ffmpeg==0.4.8
    - importlib-resources==5.12.0
    - joblib==1.2.0
    - kiwisolver==1.4.4
    - kornia==0.6.10
    - localattention==0.0.0
    - matplotlib==3.7.1
    - numpy==1.24.2
    - nvidia-ml-py==11.495.46
    - opencv-python==4.7.0.72
    - packaging==23.0
    - pandas==2.0.0
    - pathtools==0.1.2
    - pillow==9.4.0
    - positional-encodings==6.0.1
    - protobuf==4.22.1
    - psutil==5.9.4
    - pyparsing==3.0.9
    - pytz==2023.3
    - pyyaml==6.0
    - regex==2023.3.23
    - requests==2.28.2
    - scikit-learn==1.2.2
    - scipy==1.10.1
    - sentry-sdk==1.18.0
    - setproctitle==1.3.2
    - smmap==5.0.0
    - threadpoolctl==3.1.0
    - timm==0.6.13
    - tokenizers==0.13.2
    - torch==1.12.0+cu116
    - torchaudio==0.12.0+cu116
    - torchvision==0.13.0+cu116
    - tqdm==4.65.0
    - transformers==4.27.3
    - tzdata==2023.3
    - urllib3==1.26.15
    - wandb==0.14.0
    - zipp==3.15.0
prefix: /vision/hwjiang/anaconda3/envs/vq2d
