exp_name: 'eval'
exp_group: 'vq2d'
output_dir: './output/'
log_dir: './log'
workers: 0
print_freq: 100
vis_freq: 1000
eval_vis_freq: 100
seed: 42
data_dir: '../Meta/DLCV_vq2d_data'
clip_dir: '../Meta/DLCV_vq2d_data/clips'
# meta_dir: '../Meta/DLCV_vq2d_data'

# dataset config
dataset:
  name: 'ego4d_vq2d'
  query_size: 448
  clip_size_fine: 448
  clip_size_coarse: 448
  clip_num_frames: 30
  clip_num_frames_val: 30
  clip_sampling: 'rand'
  clip_reader: 'decord_balance'   # balance positive and negative samples
  frame_interval: 1
  query_padding: False
  query_square: True
  padding_value: 'mean' # ['mean', 'zero']

# model config
model:
  backbone_name: 'dinov2'
  backbone_type: 'vitb14'
  bakcbone_use_mae_weight: False
  fix_backbone: True
  num_transformer: 3
  type_transformer: 'global'
  resolution_transformer: 8
  resolution_anchor_feat: 16
  pe_transformer: 'zero'
  window_transformer: 5
  positive_threshold: 0.3
  # best checkpoint
  cpt_path: '3j3q9qsc1kovpwfxtnsful7pvdy234q6.tar'

# loss config
loss:
  weight_bbox_center: 1.0
  weight_bbox_hw: 1.0
  weight_bbox_giou: 0.3
  weight_bbox_ratio: 1.0
  weight_prob: 10.0
  prob_bce_weight: [0.1, 0.9]

# training config
train:
  resume: True
  batch_size: 1
  total_iteration: 60000
  lr: 0.0001
  weight_decay: 0.005
  schedualr_milestones: [7000, 14000, 20000, 25000]
  schedular_gamma: 0.3
  grad_max: 20.0
  accumulation_step: 1
  aug_clip: False
  aug_query: False
  aug_brightness: 0.3
  aug_contrast: 0.3
  aug_saturation: 0.2
  aug_crop_scale: 0.8
  aug_crop_ratio_min: 0.8
  aug_crop_ratio_max: 1.2
  aug_affine_degree: 90
  aug_affine_translate: 0.2
  aug_affine_scale_min: 0.8
  aug_affine_scale_max: 1.2
  aug_affine_shear_min: -15.0
  aug_affine_shear_max: 15.0
  aug_prob_color: 1.0
  aug_prob_flip: 0.5
  aug_prob_crop: 1.0
  aug_prob_affine: 1.0

# test config
test:
  batch_size: 6
  compute_metric: True